name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Compile library
      run: |
            gcc -c -fPIC -O3 crc.c
            gcc -shared crc.o -o test/crc.so
    - name: Run test
      run: python test/test.py